name: frank_the_local_llm
description: A Flutter project showcasing responsive_framework for adaptive UI.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
